package cn.monstar.payment.domain.dao;

import java.util.List;

/**
 * @author zhangshuai
 * @version 1.0
 * @description BaseMapper
 * @date 2017/11/22 16:09
 */
public interface BaseMapper<T, ID>{

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int deleteByPrimaryKey(ID id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int insert(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int insertSelective(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        T selectByPrimaryKey(ID id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int updateByPrimaryKeySelective(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int updateByPrimaryKey(T record);

        List<T> selectAll();
}
