# monstar config
monstar:
    sandboxnew: true

# wechat pay config
wx:
    appid:
    mchId:
    mchKey:
    mchCertPath:
    notifyUrl:

httpClient:
    httpConnectionTimeout: 5000
    httpTimeout: 10000
    httpProxyHost:
    # 0 disable
    httpProxyPort: 0
    httpProxyUsername:
    httpProxyPassword:

# alipay config
alipay:
    serverUrl: https://openapi.alipaydev.com/gateway.do
    alipayId: 2016090800463874
    privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCBWU0ZLWeNHySFB2jaeT6PulWnHRtQPbay+06/oJalB8TRRTo384raLh4fR6KGAXV2bBPBbS7c4JO3OKQ/s+O27bVLtifFhshaLxaNkSPyVEidoQxAOf4oWguB1GHOsIdOvP5oZBPSAICyfiolYiZ4TB6N1VJEm3ZR1JFKgt9+jPHYOsOAJida8/dcF1LSYqF+3em0XvLvWdGS9vCPLSc9AqlKSD+LrraEA3yUjfPiO77mXcGMlC3QhImiKhrvX3u04V3at40HO81Od+EUK+qvlkikIEfgBMcM+mf0s2n81NrVQy2bfmmLUyvpaUULvNbjnSyN+9s+vbscNZmgyu3LAgMBAAECggEAX6oCQXq5OUAtLE38mIhPYtF3A6+dQc1C0EDZTxSgFdIXGIdQtYzjxtWQ5aV/aAiwLTNlsQrlO+rElR/JKmwLIIHSMfq4k3hJuZlV3sHXiiQXyK0ReHbrqEBgflbrN4iLqgpRRjeuCQTiKiDxXtCmjxYNCu0YeTFZYtAJ3MfKL7dU/R6HIHdUiU80Z9BeqoZUPi/3yHj/Fk4vfH5kcbuUtVeNw1TFvXGt9dpIS74daIwy6a7QZellPSuKWi5KjlEwbfaNACMF+oJrb0vCY6+zDeiSydYg4ynqoT4FhkxZbzp0jj2sf0hPaKzH6rY/iobseJ86awyIG56HZfMTFuOFoQKBgQC4cbzjRduMb4vJmw4wA6kdaBhgQxN2bktp+14WBOKbFyoe7knl+ekC7+Yji8xs9hbZHoiJbTmLU5hKh2cdIu9pPkuK05yeiyHRSaMriD6WnFLQI/h8fyNiNHWK1yfBm8XKthV/NzSt71b+UoXGBjsBl4jH7B2Gr3gOjTNjuHvyowKBgQCzh7R/QIAMwZPxl06LYPpcD+eHj1qNRYv994BXjjBb3nVIUDZ0xMOaQBqcctnWaEOjspd3VDwUa4gZV6p4YbgA+ZiLZ8ehGdnKvi17+CWdsUfsucia9dbEtin2ihgQzzvk/QlvUv3imoQKDq94jX7sS7YnKdKm3horVgcuLORyuQKBgE9+heCWfTeb4+2ybHz5Nuw7rzXd8wd6Jfq5oiVvWZNqenb2UNdTzL+9Ub1ERYk4z0QoysQgVUrdbqfAkAqYwgLkHH7rEXerk5m2WSMsB322RmL6/d/6k++BmJ+Md9AUKT1jGQTJcGT+4MmgG5Prn4biHsu70kX4XpA2/00deB5tAoGAf/QHY+6flPferoBNfa8noLfBJ2+3dRqNNPvSYBS6SK/bXSe2ODEIzAZGMRz2PwbetmwR4f2KOG+Pd6hwmg3ja+Z4n1re/+YBwKsclc99V8/DWGftHux6HodKjylLD6fzozfpIou+4WOJGfXvf/cw787iSzVWqpF/i0VsJq/ePhkCgYAz1/ZiO9VPmBtewlo7+weT0x533Es8SGhWbZd4Wc/P6moPhK8MCmqOkTd/FTl7GYFH0DIw62xdJsXEps8bHrQ/ZocGkrucj7XqU36qt8mlk7lH8sIaM+5QnsI6to4fQKDCCglf2TSV324oFgsbAQgMd1IisBZzzJy8K+u/Ll/Wfw==
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwFbAwMZ6p5IuYhT6GKo2czPr+Abz+5OwEAJIDGHFg40/wd+u0XC1RggoESRnpbmCuFiMSXUR5pRufO9tHvx+SbFDH2bEPXI8h6okUNH9h56hfTporQklavs0ErFWyFDhREj3RR/i+dySwDJMAz8uPU7TtOUuU91/MeKsJaYRNMAhKrreMbPQ2oM1xsxU0ulLIsaKVya+rkwFE6PA9LGltFceljad88p8Njd1QCIRZznZZtYrhAip97atQ7FAMbTZ0x03wI32wo1AEymwlvsZSRTTSLmUEvfRjHWLZOZxfqTqRFLh0sc/ZofvfD47hvgLAy1NiSbTFsAbjbAxPW2IlQIDAQAB
    notifyUrl: http://42f52951.ngrok.io/callback/alipay/notify
    returnUrl:
