spring:
    datasource:
        name: syg
        url: jdbc:mysql://localhost:3306/payment?characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        password: root
        port: 6379
        timeout: 90000
    messages:
        basename: i18n/messages
mybatis:
    mapperLocations: classpath:mappers/*.xml
    type-handlers-package: cn.monstar.payment.domain.dao.mybatis
    type-aliases-package: cn.monstar.payment.domain.model.mybatis.gen
server:
    port: 2333
    servlet:
        context-path: '/'
logging:
    config: classpath:logbak.xml
    level: debug
