spring:
    datasource:
        name: syg
        #url: jdbc:mysql://localhost:3306/payment?characterEncoding=utf-8
        url: jdbc:mysql://keep-api.dyfeiyu.com:3306/payment?characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: keep-api.dyfeiyu.com
        password: wangxianding
        port: 6379
        timeout: 90000
mybatis:
    mapperLocations: classpath:mappers/*.xml
    type-handlers-package: cn.monstar.payment.domain.dao.mybatis
    type-aliases-package: cn.monstar.payment.domain.model.mybatis.gen
server:
    port: 2335
    servlet:
        context-path: '/'
    compression:
        enabled: true
        min-response-size: 2
logging:
    config: classpath:logbak.xml
    level: debug
