spring:
    datasource:
        name: syg
        url: jdbc:mysql://localhost:3306/syg
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        password: root
        port: 6379
        timeout: 300
mybatis:
    mapperLocations: classpath:mappers/*.xml
    type-handlers-package: cn.monstar.payment.domain.dao.mybatis
    type-aliases-package: cn.monstar.payment.domain.model.mybatis.gen
server:
    port: 2333
    servlet:
        context-path: '/'
    compression:
        enabled: true
        min-response-size: 2
logging:
    config: classpath:logbak.xml
    level: debug